name: cinema_app
description: AbsoluteCinema — мобильное приложение кинотеатра с бронированием билетов.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP запросы к TMDB API
  http: ^1.2.0

  # Локальное хранилище данных (избранное, брони, сессии)
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.1

  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # ── Ассеты ──────────────────────────────────────────────────
  # Добавьте файл иконки по этому пути:
  #   assets/images/app_icon.png
  # Это тот же файл, что используется как иконка приложения.
  assets:
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#0D0D0D"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  min_sdk_android: 21

    
